[package]
name = "nm"
version = "1.0.1"
description = "Native Math (NM): A tiny math library for Motoko"
repository = "https://github.com/dr-montasir/nm"
keywords = [
  "math",
  "native_math",
  "library",
  "web3",
  "icp",
  "motoko",
  "mops",
  "pkg"
]
license = "Apache-2.0"